# Custom CSS / JS modules that will be imported by the template.
# Files are relative to the static/ directory or a URL.
# Files are imported in the order they appear here, after
# theme.css and theme.js, respectively.
css_modules = []
js_modules = []

concatCssAssets = true
# Description and meta data for the search engines
author = "Moncef AOUDIA"
description = "Moncef AOUDIA's website"
keywords = "blog,personal,programming,java,graphql,springboot,quarkus,reactor,camel,apollo,opensource,multilingual"
# How many articles should be displayed at once?
paginate = 10
# Enable / Disable MathJax
enable_mathjax    = false
# Enable / Disable algolia search
algolia_search    = true
algolia_appId     = ""
algolia_apiKey    = ""
algolia_indexName = ""
# Set this option to false if you want to search within all articles in all languages at once
algolia_currentLanguageOnly = true
# Media configuration
# let hugo automatically resize and crop your images to the correct sizes
# NB: When enabled the image files get renamed by adding additional information,
#     even if the image has the correct sizes.
resizeImages = true

# Header configuration
# your subtitle if you want to use any
# subtitle = ""
# if you want to use gravatar for the header image
gravatarEMail = "mf.aoudia@gmail.com"
# avatarEmail = "mf.aoudia@gmail.com"
# set an path to the image file you want to use | overwrites gravatar
customImage = "/images/favicons/splash.webp"
# define the icon you want to use for the overlay for the customImage or gravatar.
overlayIcon = "fa-home"
# always display the top navigation (with pages and search) on non-mobile screens
permanentTopNav = true
# always display the top navigation when scrolling
# works only with permanentTopNav = true
stickyNav = false
# show a language chooser in the header
showHeaderLanguageChooser = true

enableOpenGraph = true

enableTwitterCard = true
# Content configuration
# Enable an optional pinned page to display at the top of the index
# pinnedPost = "/article/installing-bilberry-theme/"
# Set to true to pin only to the first page, false to all pages
# pinOnlyToFirstPage = true
# enable automatical localization of the article's PublishedDate with momentjs
enableMomentJs = false
# customize the date format | only works if momentjs is disabled | only works with English month names
# you can customize it with the options you find here:
# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02"
# display the estimated reading time for an article
showReadingTime = true

showPublishDate = true

showLastModificationDate = true
# Minimum word count to display the Table of Contents
tocMinWordCount = 400
# Footer configuration
showFooter = true
# How many articles should be displayed at latest posts in the footer?
# Set to -1 to hide the 'Latest Posts' column
amountLatestPostsInFooter = 10
# How many categories should be displayed in the footer section?
# Set to -1 to hide the 'Categories' column
amountCategoriesInFooter = 10
# How many series should be displayed in the footer section?
# Set to -1 to hide the 'Series' column
amountSeriesInFooter = 10
# show a language chooser in the footer
showFooterLanguageChooser = true

showFindMeOn = true
# define your links with FontAwesome 5 (only free icons are supported)
# all icons https://fontawesome.com/icons?d=gallery&m=free
# brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
socialMediaLinks = [
  { link = "https://twitter.com/aoudiamoncef", title = "Moncef AOUDIA Twitter", icon = "fab fa-twitter" },
  { link = "https://github.com/aoudiamoncef", title = "Moncef AOUDIA Github", icon = "fab fa-github" },
  { link = "https://gitlab.com/aoudiamoncef", title = "Moncef AOUDIA Gitlab", icon = "fab fa-gitlab" },
  { link = "https://www.linkedin.com/in/%F0%9F%91%A8%E2%80%8D%F0%9F%92%BB-moncef-aoudia-7723b311b", title = "Moncef AOUDIA Linkedin", icon = "fab fa-linkedin" },
  { link = "mailto:mf.aoudia@gmail.com", title = "Moncef AOUDIA Gmail", icon = "fas fa-envelope" },
  { link = "https://www.clubhouse.com/@aoudiamoncef", title = "Moncef AOUDIA Clubhouse", icon = "far fa-copyright" },
  { link = "https://discordapp.com/users/365160200900182026", title = "Moncef AOUDIA Discord", icon = "fab fa-discord" },
  { link = "https://getpocket.com/@701dbpd1T08b8g7f59Ab790A73g1T0G2725K38yf75eym1w2di86eN27V2dIJ51a", title = "Moncef AOUDIA Pocket", icon = "fab fa-get-pocket" },
  { link = "https://dev.to/aoudiamoncef", title = "Moncef AOUDIA DEV.TO", icon = "fab fa-dev" },
  { link = "https://medium.com/@aoudiamoncef", title = "Moncef AOUDIA Medium", icon = "fab fa-medium-m" },
  { link = "https://aoudiamoncef.hashnode.dev", title = "Moncef AOUDIA Hashnode", icon = "fas fa-h-square" },
  { link = "https://stackoverflow.com/users/8126192/moncef-aoudia", title = "Moncef AOUDIA Stackoverflow", icon = "fab fa-stack-overflow" },
  { link = "https://www.quora.com/profile/Moncef-AOUDIA", title = "Moncef AOUDIA Quora", icon = "fab fa-quora" },
  { link = "https://www.reddit.com/user/aoudiamoncef", title = "Moncef AOUDIA Reddit", icon = "fab fa-reddit" },
  { link = "https://slides.com/aoudiamoncef", title = "Moncef AOUDIA Slides", icon = "fas fa-sliders-h" },
  { link = "https://speakerdeck.com/aoudiamoncef", title = "Moncef AOUDIA SpeakerDeck", icon = "fab fa-speaker-deck" }
]
# credits line configuration
copyrightBy = "Moncef AOUDIA"
copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
copyrightYearOverride = "2021"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0"
creditsText = "Bilberry Hugo Theme"
creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"

sourceCodetUrl = "https://github.com/aoudiamoncef/maoudia.com"
showComments = true
# Enable / Disable Utterances comments
utterances    = true
utterancesJsUrl     = "https://utteranc.es/client.js"
utterancesRepository    = "aoudiamoncef/maoudia.com"
utterancesIssueTerm   = "pathname"
utterancesLabel   = "Comment"
utterancesTheme = "github-light"
utterancesCrossOrigin = "anonymous"

# Enable / Disable Webmentions
webmention = true

backToTop = true

enableSw = true
